# Generated by Django 3.0.5 on 2020-04-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5_hash', models.TextField()),
                ('title', models.TextField()),
                ('fullpath', models.TextField()),
                ('url', models.TextField()),
                ('file', models.FileField(default=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='LoginService.Profile')),
            ],
        ),
    ]
